services:
    # Commands
    loevgaard_dandomain_foundation.synchronize_categories_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeCategoriesCommand
        arguments:
            - "@loevgaard_dandomain_foundation.category_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_products_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeProductsCommand
        arguments:
            - "@loevgaard_dandomain_foundation.product_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_manufacturers_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeManufacturersCommand
        arguments:
            - "@loevgaard_dandomain_foundation.manufacturer_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_orders_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeOrdersCommand
        arguments:
            - "@loevgaard_dandomain_foundation.order_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_periods_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizePeriodsCommand
        arguments:
            - "@loevgaard_dandomain_foundation.period_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_shipping_methods_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeShippingMethodsCommand
        arguments:
            - "@loevgaard_dandomain_foundation.shipping_method_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_sites_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeSitesCommand
        arguments:
            - "@loevgaard_dandomain_foundation.site_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_states_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeStatesCommand
        arguments:
            - "@loevgaard_dandomain_foundation.state_synchronizer"
        tags: [console.command]

    loevgaard_dandomain_foundation.synchronize_tags_command:
        class: Loevgaard\DandomainFoundationBundle\Command\SynchronizeTagsCommand
        arguments:
            - "@loevgaard_dandomain_foundation.tag_synchronizer"
        tags: [console.command]

    # Updaters
    loevgaard_dandomain_foundation.category_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\CategoryUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.category_repository"

    loevgaard_dandomain_foundation.currency_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\CurrencyUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.currency_repository"

    loevgaard_dandomain_foundation.customer_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\CustomerUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.customer_repository"

    loevgaard_dandomain_foundation.delivery_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\DeliveryUpdater

    loevgaard_dandomain_foundation.invoice_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\InvoiceUpdater

    loevgaard_dandomain_foundation.manufacturer_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\ManufacturerUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.manufacturer_repository"

    loevgaard_dandomain_foundation.order_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\OrderUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.order_repository"
            - "@loevgaard_dandomain_foundation.product_repository"
            - "@loevgaard_dandomain_foundation.product_synchronizer"
            - "@loevgaard_dandomain_foundation.shipping_method_updater"
            - "@loevgaard_dandomain_foundation.payment_method_updater"
            - "@loevgaard_dandomain_foundation.site_repository"
            - "@loevgaard_dandomain_foundation.site_synchronizer"
            - "@loevgaard_dandomain_foundation.state_updater"
            - "@loevgaard_dandomain_foundation.customer_updater"
            - "@loevgaard_dandomain_foundation.delivery_updater"
            - "@loevgaard_dandomain_foundation.invoice_updater"
            - "@loevgaard_dandomain_foundation.currency_repository"
            - "@loevgaard_dandomain_foundation.currency_synchronizer"

    loevgaard_dandomain_foundation.payment_method_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\PaymentMethodUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.payment_method_repository"

    loevgaard_dandomain_foundation.period_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\PeriodUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.period_repository"

    loevgaard_dandomain_foundation.product_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\ProductUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.product_repository"
            - "@loevgaard_dandomain_foundation.manufacturer_repository"
            - "@loevgaard_dandomain_foundation.variant_group_repository"

    loevgaard_dandomain_foundation.shipping_method_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\ShippingMethodUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.shipping_method_repository"

    loevgaard_dandomain_foundation.site_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\SiteUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.site_repository"
            - "@loevgaard_dandomain_foundation.currency_repository"
            - "@loevgaard_dandomain_foundation.currency_synchronizer"

    loevgaard_dandomain_foundation.state_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\StateUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.state_repository"

    loevgaard_dandomain_foundation.tag_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\TagUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.tag_repository"
            - "@loevgaard_dandomain_foundation.tag_value_updater"

    loevgaard_dandomain_foundation.tag_value_updater:
        class: Loevgaard\DandomainFoundationBundle\Updater\TagValueUpdater
        arguments:
            - "@loevgaard_dandomain_foundation.tag_value_repository"

    # Synchronizers
    loevgaard_dandomain_foundation.category_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\CategorySynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.category_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.category_updater"

    loevgaard_dandomain_foundation.currency_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\CurrencySynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.currency_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.currency_updater"

    loevgaard_dandomain_foundation.period_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\PeriodSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.period_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.period_updater"

    loevgaard_dandomain_foundation.product_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\ProductSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.product_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.product_updater"

    loevgaard_dandomain_foundation.manufacturer_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\ManufacturerSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.manufacturer_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.manufacturer_updater"

    loevgaard_dandomain_foundation.order_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\OrderSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.order_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.order_updater"

    loevgaard_dandomain_foundation.payment_method_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\PaymentMethodSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.payment_method_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.payment_method_updater"
            - "@loevgaard_dandomain_foundation.site_repository"

    loevgaard_dandomain_foundation.shipping_method_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\ShippingMethodSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.shipping_method_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.shipping_method_updater"

    loevgaard_dandomain_foundation.site_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\SiteSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.site_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.site_updater"

    loevgaard_dandomain_foundation.state_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\StateSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.state_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.state_updater"

    loevgaard_dandomain_foundation.tag_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\TagSynchronizer
        arguments:
            - "@loevgaard_dandomain_foundation.tag_repository"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.synchronizer_logs_dir%"
            - "@loevgaard_dandomain_foundation.tag_updater"

    # Repositories
    loevgaard_dandomain_foundation.category_repository:
        class: Loevgaard\DandomainFoundation\Repository\CategoryRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.currency_repository:
        class: Loevgaard\DandomainFoundation\Repository\CurrencyRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.customer_repository:
        class: Loevgaard\DandomainFoundation\Repository\CustomerRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.manufacturer_repository:
        class: Loevgaard\DandomainFoundation\Repository\ManufacturerRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.order_repository:
        class: Loevgaard\DandomainFoundation\Repository\OrderRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.payment_method_repository:
        class: Loevgaard\DandomainFoundation\Repository\PaymentMethodRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.period_repository:
        class: Loevgaard\DandomainFoundation\Repository\PeriodRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.product_repository:
        class: Loevgaard\DandomainFoundation\Repository\ProductRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.product_type_repository:
        class: Loevgaard\DandomainFoundation\Repository\ProductTypeRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.shipping_method_repository:
        class: Loevgaard\DandomainFoundation\Repository\ShippingMethodRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.site_repository:
        class: Loevgaard\DandomainFoundation\Repository\SiteRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.state_repository:
        class: Loevgaard\DandomainFoundation\Repository\StateRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.tag_repository:
        class: Loevgaard\DandomainFoundation\Repository\TagRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.tag_value_repository:
        class: Loevgaard\DandomainFoundation\Repository\TagValueRepository
        arguments:
            - "@doctrine"

    loevgaard_dandomain_foundation.variant_group_repository:
        class: Loevgaard\DandomainFoundation\Repository\VariantGroupRepository
        arguments:
            - "@doctrine"
