services:
    dandomain_foundation.customer_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\CustomerSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.customer_class%"

    dandomain_foundation.order_service:
        class: Loevgaard\DandomainFoundationBundle\Service\OrderService
        arguments:
            - "@dandomain.api"
            - "@doctrine.orm.entity_manager"
            - "@dandomain_foundation.order_synchronizer"

    dandomain_foundation.order_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\OrderSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.order_class%"
        calls:
            - [setCustomerSynchronizer, ["@dandomain_foundation.customer_synchronizer"]]
