services:
    dandomain_foundation.customer_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\CustomerSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.customer_class%"

    dandomain_foundation.delivery_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\DeliverySynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.delivery_class%"

    dandomain_foundation.invoice_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\InvoiceSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.invoice_class%"

    dandomain_foundation.order_service:
        class: Loevgaard\DandomainFoundationBundle\Service\OrderService
        arguments:
            - "@dandomain.api"
            - "@doctrine.orm.entity_manager"
            - "@dandomain_foundation.order_synchronizer"

    dandomain_foundation.order_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\OrderSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.order_class%"
        calls:
            - [setCustomerSynchronizer, ["@dandomain_foundation.customer_synchronizer"]]
            - [setDeliverySynchronizer, ["@dandomain_foundation.delivery_synchronizer"]]
            - [setInvoiceSynchronizer, ["@dandomain_foundation.invoice_synchronizer"]]
            - [setPaymentMethodSynchronizer, ["@dandomain_foundation.payment_method_synchronizer"]]
            - [setShippingMethodSynchronizer, ["@dandomain_foundation.shipping_method_synchronizer"]]

    dandomain_foundation.payment_method_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\PaymentMethodSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.payment_method_class%"

    dandomain_foundation.shipping_method_synchronizer:
        class: Loevgaard\DandomainFoundationBundle\Synchronizer\ShippingMethodSynchronizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@dandomain.api"
            - "%loevgaard_dandomain_foundation.shipping_method_class%"
